+incdir+../../src/globals/ \
+incdir+../../src/hvl_top/test/sequences/device0_sequences/ \
+incdir+../../src/hvl_top/Device0/ \
+incdir+../../src/hdl_top/device0_agent_bfm/  \
+incdir+../../src/hvl_top/env/virtual_sequencer/ \
+incdir+../../src/hvl_top/test/virtual_sequences/ \
+incdir+../../src/hvl_top/env \
+incdir+../../src/hvl_top/Device1 \
+incdir+../../src/hvl_top/test/sequences/device1_sequences/ \
+incdir+../../src/hvl_top/test \
+incdir+../../src/hdl_top/device1_agent_bfm \
+incdir+../../src/hdl_top/uart_interface \
../../src/globals/uart_globals_pkg.sv \
../../src/hvl_top/Device0/uart_device0_pkg.sv \
../../src/hvl_top/Device1/uart_device1_pkg.sv \
../../src/hvl_top/test/sequences/device0_sequences/device0_uart_seq_pkg.sv \
../../src/hvl_top/test/sequences/device1_sequences/device1_uart_seq_pkg.sv \
../../src/hvl_top/env/uart_env_pkg.sv \
../../src/hvl_top/test/virtual_sequences/uart_virtual_seq_pkg.sv \
../../src/hvl_top/test/test_pkg.sv \
../../src/hdl_top/uart_interface/uart_if.sv \
../../src/hdl_top/device0_agent_bfm/device0_driver_bfm.sv \
../../src/hdl_top/device0_agent_bfm/device0_monitor_bfm.sv \
../../src/hdl_top/device0_agent_bfm/device0_agent_bfm.sv \
../../src/hdl_top/device1_agent_bfm/device1_driver_bfm.sv \
../../src/hdl_top/device1_agent_bfm/device1_monitor_bfm.sv \
../../src/hdl_top/device1_agent_bfm/device1_agent_bfm.sv \
../../src/hdl_top/hdl_top.sv \
../../src/hvl_top/hvl_top.sv 

